import { WorkflowAgentPage, type WorkflowPageConfig } from '../sharedWorkflow';

const config: WorkflowPageConfig = {
  agentTitle: 'Credit Support — Hỗ trợ tín dụng',
  agentSubtitle: 'Cty TNHH ABC · REQ-2026-00458',
  agentIcon: 'CS',
  welcomeTitle: 'Checklist giải ngân còn 2 điều kiện mở',
  welcomeText: 'Hợp đồng tín dụng, thế chấp và đăng ký giao dịch bảo đảm đã hoàn tất. Còn thiếu giải trình doanh thu và biên bản thực địa TSBĐ.',
  chips: ['Còn thiếu điều kiện gì để giải ngân?', 'Xem nội dung hợp đồng tín dụng', 'Đăng ký GDBĐ (NPAST) là gì?', 'Lịch sử nhắc khách hàng'],
  banner: 'Hợp đồng & giải ngân — theo dõi checklist điều kiện theo thời gian thực.',
  loadingText: 'Cập nhật checklist điều kiện giải ngân.',
  progress: ['Credit contract signed', 'Mortgage contract notarized', 'Secured transaction registered', 'Customer conditions checked', 'Collateral field-check condition checked'],
  summaryTitle: 'Checklist điều kiện giải ngân',
  cards: [
    {
      tone: 'good',
      title: 'Hợp đồng tín dụng đã ký',
      description: 'Hoàn tất ký kết giữa SHB và Cty TNHH ABC.',
      evidence: 'Signed credit contract · 15/07/2026',
      rule: 'Required before disbursement.',
      action: 'Không cần xử lý thêm.',
      confidence: 'High · signed document present',
      meta: '15/07/2026',
    },
    {
      tone: 'good',
      title: 'Hợp đồng thế chấp đã công chứng',
      description: 'Công chứng tại Văn phòng công chứng Q9.',
      evidence: 'Notarized mortgage contract · 16/07/2026',
      rule: 'Collateral contract must be notarized before secured transaction registration.',
      action: 'Không cần xử lý thêm.',
      confidence: 'High · notarization record present',
      meta: '16/07/2026',
    },
    {
      tone: 'good',
      title: 'Đăng ký giao dịch bảo đảm',
      description: 'Đăng ký thành công trên hệ thống NPAST.',
      evidence: 'NPAST registration receipt · 16/07/2026',
      rule: 'Required before disbursement against collateral.',
      action: 'Không cần xử lý thêm.',
      confidence: 'High · registration receipt present',
      meta: '16/07/2026',
    },
    {
      tone: 'critical',
      title: 'Chưa có giải trình doanh thu',
      description: 'Chờ khách hàng cung cấp giải trình chênh lệch BCTC ↔ thuế 25%.',
      evidence: 'Approval condition; Financial review revenue variance',
      rule: 'Block disbursement until customer explanation is accepted.',
      action: 'Gửi nhắc khách hàng và RM phụ trách.',
      confidence: 'High · open condition from approval',
      meta: 'Chờ khách hàng',
    },
    {
      tone: 'warning',
      title: 'Chờ biên bản thực địa TSBĐ',
      description: 'Chờ cán bộ hoàn tất thực địa tài sản bảo đảm tại Q9.',
      evidence: 'Approval condition; Collateral review field-check request',
      rule: 'Must be completed before final disbursement release.',
      action: 'Giao việc cho cán bộ thực địa.',
      confidence: 'Medium · pending field report upload',
      meta: 'Chờ cán bộ',
    },
  ],
  footerHint: 'Chưa thể giải ngân khi còn điều kiện mở.',
  secondaryLabel: 'Gửi nhắc KH',
  primaryLabel: 'Sang giám sát danh mục',
  blocker: 'Còn 1 blocker — chưa có giải trình doanh thu',
  nextRoute: 'portfolioMonitoring',
};

export function LoanDisbursementPage({ params }: { params: Record<string, string> }) {
  return <WorkflowAgentPage config={config} caseId={params.caseId} />;
}
